#include "system16b_audio.h"
#include "system16b_machine.h"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <vector>

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "Usage: %s <shinobi_rom> [frames]\n", argv[0]);
        return 2;
    }
    const int frame_count = argc >= 3 ? std::atoi(argv[2]) : 900;
    system16b::system16b_machine_t machine;
    if (!machine.load_roms(argv[1])) return 3;

    system16b_sound_synth synth;
    uint8_t ym_address = 0;
    unsigned ym_writes = 0;
    unsigned key_ons = 0;
    machine.set_sound_write_callback(
        [&](unsigned port, uint8_t data) {
            synth.write_control(port, data);
            if (port == 0) {
                ym_address = data;
            } else if (port == 1) {
                ++ym_writes;
                if (ym_address == 0x08 && (data & 0x78) != 0) ++key_ons;
            }
        });
    machine.set_sound_status_callback([&] { return synth.read_status(); });
    machine.set_sound_timer_callback(
        [&](uint32_t clocks) { synth.advance_timer_clocks(clocks); });
    machine.reset();

    std::vector<int16_t> samples(800 * 2);
    int peak = 0;
    for (int frame = 0; frame < frame_count; ++frame) {
        input_state input;
        // Exercise the same edge pulses generated by keyboard/controller
        // input so the integration run enters a game as well as attract mode.
        input.coin1 = frame == 120 || frame == 121;
        input.start = frame >= 150 && frame <= 153;
        machine.set_input(input);
        machine.run_frame();
        synth.generate(samples.data(), 800);
        for (int16_t sample : samples)
            peak = std::max(peak, std::abs(static_cast<int>(sample)));
    }

    std::printf("shinobi audio integration: frames=%d ym_writes=%u "
                "key_ons=%u peak=%d\n",
                frame_count, ym_writes, key_ons, peak);
    return (ym_writes != 0 && key_ons != 0 && peak != 0) ? 0 : 1;
}
