// Vulkan port of model2_fragment_shader_source in src/arcade_renderer.cpp:
// Model 2 texture-sheet decoding, bilinear filtering, luma and colour tables.
// Generated by transforming the OpenGL original so the texel arithmetic is
// character-for-character the same; only resource declarations, explicit
// locations and the fragment-origin convention differ.
#version 450
layout(location = 0) in vec2 texture_uv;
layout(location = 1) flat in vec4 clip_rect;
layout(location = 2) flat in uint header0;
layout(location = 3) flat in uint header1;
layout(location = 4) flat in uint header2;
layout(location = 5) flat in uint color_base;
layout(location = 6) flat in uint polygon_luma;
layout(location = 7) flat in uint renderer;
layout(location = 8) flat in int texture_lod;
layout(location = 9) flat in float object_priority;

layout(set = 0, binding = 0) uniform usampler2DArray texture_sheets;
layout(set = 0, binding = 1) uniform usampler2D luma_table;
layout(set = 0, binding = 2) uniform sampler2D color_table;
layout(location = 0) out vec4 output_color;

uint sheet_byte(uint layer, uint address) {
    return texelFetch(texture_sheets,
        ivec3(int(address & 1023u), int(address >> 10u), int(layer)), 0).r;
}

uint model2_texel_at(int base_x, int base_y, int x, int y,
                     int level, bool microtexture) {
    int sheet_x = base_x + x;
    int sheet_y = base_y + y;
    if (sheet_x >= 1024) {
        sheet_x -= 1024;
        sheet_y ^= 1024;
    }
    uint packed_index = uint((sheet_y / 2) * 512 + sheet_x / 2);
    uint address = (packed_index >> 1u) * 4u +
                   ((packed_index & 1u) * 2u);
    uint base_layer = (header2 & 0x1000u) != 0u ? 1u : 0u;
    uint layer = microtexture ? (base_layer ^ 1u) :
                                (base_layer ^ uint(level & 1));
    uint value = sheet_byte(layer, address) |
                 (sheet_byte(layer, address + 1u) << 8u);
    if ((y & 1) == 0) value >>= 8u;
    if ((x & 1) == 0) value >>= 4u;
    return value & 15u;
}

uint model2_lerp(uint first, uint second, uint amount) {
    return (first + (((second - first) * amount) >> 8u)) & 0x00ff00ffu;
}

uint model2_filtered_texel(int level, int u, int v, bool microtexture) {
    int width;
    int height;
    int base_x;
    int base_y;
    if (microtexture) {
        width = 128;
        height = 128;
        base_x = int((header2 >> 13u) & 1u) * 128;
        base_y = int((header2 >> 14u) & 3u) * 128;
        int coordinate_shift = 1 << int((header0 >> 10u) & 3u);
        u = int(uint(u) << coordinate_shift);
        v = int(uint(v) << coordinate_shift);
        level = 0;
    } else {
        width = (32 << int(header0 & 7u)) >> level;
        height = (32 << int((header0 >> 3u) & 7u)) >> level;
        base_x = ((32 * int(header2 & 0x3fu) - 2048) >> level) & 2047;
        base_y = ((32 * int((header2 >> 6u) & 0x1fu) - 1024) >> level) & 1023;
        u >>= level;
        v >>= level;
    }

    bool mirror_x = (header0 & 0x100u) != 0u;
    bool mirror_y = (header0 & 0x200u) != 0u;
    bool wrap_x = (header0 & 0x040u) != 0u && !mirror_x;
    bool wrap_y = (header0 & 0x080u) != 0u && !mirror_y;
    if (mirror_x && (u & (width << 8)) != 0) u = ~u;
    if (mirror_y && (v & (height << 8)) != 0) v = ~v;

    u -= 0x80;
    v -= 0x80;
    uint u_fraction = uint(u) & 0xffu;
    uint v_fraction = uint(v) & 0xffu;
    int u0 = (u >> 8) & (width - 1);
    int u1 = (u0 + 1) & (width - 1);
    int v0 = (v >> 8) & (height - 1);
    int v1 = (v0 + 1) & (height - 1);
    if (!wrap_x && u1 == 0) {
        if (u_fraction >= 0x80u) {
            u0 = u1;
            ++u1;
            u_fraction = 0u;
        } else {
            u1 = u0;
            --u0;
            u_fraction = 0x100u;
        }
    }
    if (!wrap_y && v1 == 0) {
        if (v_fraction >= 0x80u) {
            v0 = 0;
            ++v1;
            v_fraction = 0u;
        } else {
            v1 = v0;
            --v0;
            v_fraction = 0x100u;
        }
    }

    uint tex00 = model2_texel_at(base_x, base_y, u0, v0,
                                 level, microtexture) << 4u;
    uint tex01 = model2_texel_at(base_x, base_y, u1, v0,
                                 level, microtexture) << 4u;
    uint tex10 = model2_texel_at(base_x, base_y, u0, v1,
                                 level, microtexture) << 4u;
    uint tex11 = model2_texel_at(base_x, base_y, u1, v1,
                                 level, microtexture) << 4u;
    if (renderer == 3u) {
        if (tex00 != 0xf0u) tex00 |= 0x00800000u;
        if (tex01 != 0xf0u) tex01 |= 0x00800000u;
        if (tex10 != 0xf0u) tex10 |= 0x00800000u;
        if (tex11 != 0xf0u) tex11 |= 0x00800000u;
        if (tex00 == 0x000000f0u) tex00 = tex01 & 0xffu;
        if (tex01 == 0x000000f0u) tex01 = tex00 & 0xffu;
        if (tex10 == 0x000000f0u) tex10 = tex11 & 0xffu;
        if (tex11 == 0x000000f0u) tex11 = tex10 & 0xffu;
    }
    uint top = model2_lerp(tex00, tex01, u_fraction);
    uint bottom = model2_lerp(tex10, tex11, u_fraction);
    if (renderer == 3u) {
        if (top == 0x000000f0u) top = bottom & 0xffu;
        if (bottom == 0x000000f0u) bottom = top & 0xffu;
    }
    return model2_lerp(top, bottom, v_fraction);
}

void main() {
    int screen_x = int(gl_FragCoord.x);
    // Vulkan's fragment origin is already the top-left and the vertex
    // stage flips clip-space Y to match, so the OpenGL "383 -" flip
    // would invert the clip rectangle a second time.
    int screen_y = int(gl_FragCoord.y);
    if (screen_x < int(clip_rect.x) || screen_x > int(clip_rect.y) ||
        screen_y < int(clip_rect.z) || screen_y > int(clip_rect.w))
        discard;
    if ((header0 & 0x8000u) != 0u &&
        ((screen_x ^ screen_y) & 1) == 0)
        discard;

    uint luma = min(polygon_luma >> 2u, 63u);
    if ((renderer & 2u) != 0u) {
        int width = 32 << int(header0 & 7u);
        int height = 32 << int((header0 >> 3u) & 7u);
        int maximum_level = findMSB(min(width, height)) - 1;
        float camera_z = 1.0 / max(gl_FragCoord.w, 1.0e-30);
        int mml = -texture_lod + int(round(log2(camera_z) * 256.0));
        int level = clamp(mml >> 7, 0, maximum_level);
        int u = int(texture_uv.x * 256.0);
        int v = int(texture_uv.y * 256.0);
        uint sample_value = model2_filtered_texel(level, u, v, false);
        if (mml > 0 && level < maximum_level) {
            uint next_value = model2_filtered_texel(level + 1, u, v, false);
            sample_value = model2_lerp(
                sample_value, next_value, uint(mml & 127) << 1u);
        } else if ((header0 & 0x1000u) != 0u && mml < 0) {
            uint micro_value = model2_filtered_texel(0, u, v, true);
            int minimum_lod = int((header0 >> 10u) & 3u);
            uint amount = uint(min((-mml) >> minimum_lod, 127));
            sample_value = model2_lerp(sample_value, micro_value, amount);
        }
        if (renderer == 3u && sample_value < 0x00400000u) discard;
        uint texel_luma = (sample_value & 0xffu) >> 1u;
        uint luma_address = ((header1 & 255u) << 7u) + texel_luma;
        uint texture_luma = texelFetch(luma_table,
            ivec2(int(luma_address & 255u), int(luma_address >> 8u)), 0).r;
        luma = min((texture_luma * polygon_luma) >> 8u, 63u);
    }
    vec3 rgb = texelFetch(color_table,
        ivec2(int(color_base & 1023u), int(luma)), 0).rgb;
    // Model 2 has no per-pixel camera-Z test.  Its geometrizer places each
    // polygon in a 16-bit Z-sort bucket, then the rasterizer draws the
    // buckets front-to-back into a one-bit fill buffer.  Once a pixel is
    // filled, a later polygon cannot replace it.  Using interpolated camera
    // Z here lets large road polygons overwrite cars whose object-level
    // Z-sort deliberately places them in front, making the cars vanish as
    // the camera moves.  polygon_order already matches the hardware bucket
    // and linked-list order, so use that order as the depth value directly.
    gl_FragDepth = object_priority;
    output_color = vec4(rgb, 1.0);
}
