// Vulkan port of model2_vertex_shader_source in src/arcade_renderer.cpp.
// Generated by transforming the OpenGL original: the arithmetic is untouched,
// only the resource declarations, the explicit varying locations Vulkan
// requires, and the clip-space Y direction differ.
#version 450
layout(location = 0) in vec3 in_position;
layout(location = 1) in vec2 in_uv;
layout(location = 2) in vec2 in_center;
layout(location = 3) in vec4 in_clip;
layout(location = 4) in float in_header0;
layout(location = 5) in float in_header1;
layout(location = 6) in float in_header2;
layout(location = 7) in float in_color_base;
layout(location = 8) in float in_luma;
layout(location = 9) in float in_renderer;
layout(location = 10) in float in_texture_lod;
layout(location = 11) in float in_draw_priority;

layout(push_constant) uniform model2_constants {
    vec2 crtc_offset;
} constants;
layout(location = 0) out vec2 texture_uv;
layout(location = 1) flat out vec4 clip_rect;
layout(location = 2) flat out uint header0;
layout(location = 3) flat out uint header1;
layout(location = 4) flat out uint header2;
layout(location = 5) flat out uint color_base;
layout(location = 6) flat out uint polygon_luma;
layout(location = 7) flat out uint renderer;
layout(location = 8) flat out int texture_lod;
layout(location = 9) flat out float object_priority;

void main() {
    float z = in_position.z;
    float center_x = constants.crtc_offset.x + in_center.x;
    float center_y = 384.0 - in_center.y + constants.crtc_offset.y;
    float clip_x = ((2.0 * center_x / 496.0) - 1.0) * z +
                   (2.0 * in_position.x / 496.0);
    float clip_y = (1.0 - (2.0 * center_y / 384.0)) * z +
                   (2.0 * in_position.y / 384.0);
    // Vulkan clip space is +Y down, the board's is +Y up.
    gl_Position = vec4(clip_x, -clip_y, 0.0, z);
    texture_uv = in_uv;
    clip_rect = in_clip;
    header0 = uint(in_header0);
    header1 = uint(in_header1);
    header2 = uint(in_header2);
    color_base = uint(in_color_base);
    polygon_luma = uint(in_luma);
    renderer = uint(in_renderer);
    texture_lod = int(in_texture_lod);
    object_priority = in_draw_priority;
}
